### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by Nabagata** [JeeveshN/Face-Extractor#3]
How are the extracted files named?

**Comment by JeeveshN** [comment]
A random integer is chosen from 1 to 10000.

**Comment by Ravsehajsinghpuri** [comment]
How can I specify the naming convention?
Like if I have 100 images and I want them to be named as 1.png..2.png and so on.
Secondly, if I have multiple faces in an image.... for example an image number 50 has 3 faces in it then I want the 3 faces to be extracted and saved as 50_1.png 50_2.png 50_3.png.
